//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Inputs/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""General"",
            ""id"": ""4dd88877-f6ee-437e-883c-acc98ce723e5"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""5b22dc57-f197-44d2-adee-558714ba700b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Sleep"",
                    ""type"": ""Button"",
                    ""id"": ""0aac306d-e381-4437-b672-d48fa61a2eef"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Gather"",
                    ""type"": ""Button"",
                    ""id"": ""4b6b990f-7c76-4f51-b6f4-3781b9c760e3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Observe"",
                    ""type"": ""Button"",
                    ""id"": ""698e477e-9b06-40ba-9506-6dbc21dcda01"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Create"",
                    ""type"": ""Button"",
                    ""id"": ""e2b23358-295d-42d8-a36c-3da8de285dc8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zoom "",
                    ""type"": ""PassThrough"",
                    ""id"": ""0e48472f-b86e-464d-a57d-85eb02d9ce4e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7547b342-09fe-4758-8fc2-4b23b12fabec"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Desktop Control Scheme"",
                    ""action"": ""Sleep"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dd5b41b3-441e-4570-8c98-0c71e3c6ec9b"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Desktop Control Scheme"",
                    ""action"": ""Gather"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""952a0dbb-e648-4f49-a056-68a95111ac11"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Desktop Control Scheme"",
                    ""action"": ""Observe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a8ee03e-247c-4499-9aa7-c1d11db54b7a"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Desktop Control Scheme"",
                    ""action"": ""Create"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""228757d0-cb21-4bb9-b2f2-658fe11c776f"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Desktop Control Scheme"",
                    ""action"": ""Zoom "",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""1faf747e-d09a-4e90-86b1-e94d7c9def3f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""762f57db-9140-4d0c-bbe5-49cf4cf377e1"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Desktop Control Scheme"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""cecc98dd-64fb-485a-af20-52381531a1b0"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Desktop Control Scheme"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""99157616-9cbf-4ff2-956d-a27af9687197"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Desktop Control Scheme"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""cc29d499-9f72-4caf-a717-63202d461a37"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Desktop Control Scheme"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrow Keys"",
                    ""id"": ""1bba3533-b0d0-457a-b876-37cf89714cda"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b01a991b-82c2-4dcc-a4ae-6e34cf7a2d18"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Desktop Control Scheme"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""70972769-2f37-41d5-98bc-dee39cb8e638"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Desktop Control Scheme"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1764561e-06c5-4ff6-84cd-3a079476a8e6"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Desktop Control Scheme"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""befb9186-65b3-4d00-a981-4c2fdd990df0"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Desktop Control Scheme"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Desktop Control Scheme"",
            ""bindingGroup"": ""Desktop Control Scheme"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // General
        m_General = asset.FindActionMap("General", throwIfNotFound: true);
        m_General_Move = m_General.FindAction("Move", throwIfNotFound: true);
        m_General_Sleep = m_General.FindAction("Sleep", throwIfNotFound: true);
        m_General_Gather = m_General.FindAction("Gather", throwIfNotFound: true);
        m_General_Observe = m_General.FindAction("Observe", throwIfNotFound: true);
        m_General_Create = m_General.FindAction("Create", throwIfNotFound: true);
        m_General_Zoom = m_General.FindAction("Zoom ", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // General
    private readonly InputActionMap m_General;
    private IGeneralActions m_GeneralActionsCallbackInterface;
    private readonly InputAction m_General_Move;
    private readonly InputAction m_General_Sleep;
    private readonly InputAction m_General_Gather;
    private readonly InputAction m_General_Observe;
    private readonly InputAction m_General_Create;
    private readonly InputAction m_General_Zoom;
    public struct GeneralActions
    {
        private @PlayerControls m_Wrapper;
        public GeneralActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_General_Move;
        public InputAction @Sleep => m_Wrapper.m_General_Sleep;
        public InputAction @Gather => m_Wrapper.m_General_Gather;
        public InputAction @Observe => m_Wrapper.m_General_Observe;
        public InputAction @Create => m_Wrapper.m_General_Create;
        public InputAction @Zoom => m_Wrapper.m_General_Zoom;
        public InputActionMap Get() { return m_Wrapper.m_General; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GeneralActions set) { return set.Get(); }
        public void SetCallbacks(IGeneralActions instance)
        {
            if (m_Wrapper.m_GeneralActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnMove;
                @Sleep.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnSleep;
                @Sleep.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnSleep;
                @Sleep.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnSleep;
                @Gather.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnGather;
                @Gather.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnGather;
                @Gather.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnGather;
                @Observe.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnObserve;
                @Observe.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnObserve;
                @Observe.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnObserve;
                @Create.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnCreate;
                @Create.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnCreate;
                @Create.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnCreate;
                @Zoom.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnZoom;
                @Zoom.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnZoom;
                @Zoom.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnZoom;
            }
            m_Wrapper.m_GeneralActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Sleep.started += instance.OnSleep;
                @Sleep.performed += instance.OnSleep;
                @Sleep.canceled += instance.OnSleep;
                @Gather.started += instance.OnGather;
                @Gather.performed += instance.OnGather;
                @Gather.canceled += instance.OnGather;
                @Observe.started += instance.OnObserve;
                @Observe.performed += instance.OnObserve;
                @Observe.canceled += instance.OnObserve;
                @Create.started += instance.OnCreate;
                @Create.performed += instance.OnCreate;
                @Create.canceled += instance.OnCreate;
                @Zoom.started += instance.OnZoom;
                @Zoom.performed += instance.OnZoom;
                @Zoom.canceled += instance.OnZoom;
            }
        }
    }
    public GeneralActions @General => new GeneralActions(this);
    private int m_DesktopControlSchemeSchemeIndex = -1;
    public InputControlScheme DesktopControlSchemeScheme
    {
        get
        {
            if (m_DesktopControlSchemeSchemeIndex == -1) m_DesktopControlSchemeSchemeIndex = asset.FindControlSchemeIndex("Desktop Control Scheme");
            return asset.controlSchemes[m_DesktopControlSchemeSchemeIndex];
        }
    }
    public interface IGeneralActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnSleep(InputAction.CallbackContext context);
        void OnGather(InputAction.CallbackContext context);
        void OnObserve(InputAction.CallbackContext context);
        void OnCreate(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
    }
}
